### ISSUE TITLE
Add .gitignore with content "*" in process output

### ISSUE THREAD

**Issue by lntsmn** [madnklo/madnklo#17]
Since we know that process outputs should (by default) not be committed, it would be useful to generate a `.gitignore` with content "*" in the corresponding folder within `do_output`.

**Comment by ndeutschmann** [comment]
How would you want to do this?
The only easy way I see would be to enforce a given prefix for processes so that we can tag them. Is there another way?

**Comment by lntsmn** [comment]
No I meant generate the file directly *in* the process folder when `output` is invoked.

**Comment by ndeutschmann** [comment]
Fixed in 3a0368427b535a0ddad3cd6c51e0d47bc07f6ace
