### ISSUE TITLE
Incorrect normalization in beam_soft integrated ct

### ISSUE THREAD

**Issue by ndeutschmann** [madnklo/madnklo#3]
In `madgraph.iolibs.template_files.subtraction.colorful_pp.NLO.beam_factorization.QCD_beam_factorization_single_soft#evaluate_kernel` a `prefactor` is defined:

```
prefactor = EpsilonExpansion({ 0 : 1., 1 : logMuQ, 2 : 0.5*logMuQ**2 })
prefactor *= normalization
```

where `normalization` is passed as a function argument. However the final result is multiplied only by `normalization`, not by `prefactor`. This affects O(1) terms due to poles.

**Comment by ValentinHirschi** [comment]
Indeed, this should be fixed!

**Comment by ndeutschmann** [comment]
Fixed in revno 609
