### ISSUE TITLE
Multiplicity factors in ISR branch

### ISSUE THREAD

**Issue by lntsmn** [madnklo/madnklo#6]
Executing the commands
```
set subtraction_mappings_scheme FinalGroupingDisjoint 
set subtraction_currents_scheme colorful
generate e+ e- > j j j j / z --NNLO=QCD --ignore_contributions=V,RV,VV
output ee2jjjj_issue_doublecoll --ignore_integrated_counterterms=all
launch ee2jjjj_issue_doublecoll/
test_IR_limits --process=e+ e- > u u~ d d~ s s~ --min_scaling_variable=1e-16 --n_steps=100 --limits=(C(3,6),C(4,8),) --walker=FinalLorentzNLO --counterterms=(C(3,6),)|(C(4,8),)|(C(3,6),C(4,8),) --seed=1 --ignore_flavors
```
Shows that the limits `C(3,6)` and `C(4,8)` differ by a factor of 2, which cannot derive from currents and probably has something to do with flavour mappings.

**Comment by ndeutschmann** [comment]
Just a reminder that as of now in the master branch, e+e- > j j j does *not* work if `group_subprocessse` is `True` (528d5868adc7fccd554eaa781c794588b4eb0581)

**Comment by ValentinHirschi** [comment]
This was a relatively simple issue related to the multiplicity of reduced flavours which was not accounted for.
